#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/codex-hook-test.out 2>/tmp/codex-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_denies_2() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        hook_status=0
    else
        hook_status=$?
    fi
    if [ "$hook_status" -eq 2 ]; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s returned %s instead of 2\n' "$label" "$hook_status" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_blocks "blocks attribution in Write content" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\nprint(1)\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"codex/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

# no_ai_attribution_bash.py reads its agent names from git/hooks/agent-tokens.
# Names are built from parts so this file never holds a literal attribution.
ATTR_HOOK=codex/hooks/no_ai_attribution_bash.py
ATTR_NEW_NAME="Gem""ini"
ATTR_SHARED_NAME="Co""dex"
ATTR_GEN_PAYLOAD="{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"gh pr comment 1 --body 'Generated with ${ATTR_NEW_NAME}'\"}}"

assert_denies_2 "attribution bash: blocks generated-with naming a new token" \
    "$ATTR_HOOK" "$ATTR_GEN_PAYLOAD"

assert_denies_2 "attribution bash: blocks a co-author naming a shared token" \
    "$ATTR_HOOK" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m x -m 'Co-Authored-By: ${ATTR_SHARED_NAME} <bot@example.com>'\"}}"

assert_allows "attribution bash: allows a human surname containing a token" \
    "$ATTR_HOOK" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m x -m 'Co-Authored-By: Jane Raider <jane@example.com>'\"}}"

ATTR_PREFIXED_NAME="Auto""GPT"
assert_denies_2 "attribution bash: blocks a co-author with a prefix glued in front of a token" \
    "$ATTR_HOOK" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m x -m 'Co-Authored-By: ${ATTR_PREFIXED_NAME} <agent@example.com>'\"}}"

# The hook resolves agent-tokens from its own path, so a copy in a temp tree
# sees only that tree's token file.
for case in missing empty invalid crlf; do
    tree="$(mktemp -d "${TMPDIR:-/tmp}/attr-tokens.XXXXXX")"
    mkdir -p "$tree/codex/hooks" "$tree/git/hooks"
    cp "$ATTR_HOOK" "$tree/codex/hooks/"
    if [ "$case" = empty ]; then
        : >"$tree/git/hooks/agent-tokens"
    elif [ "$case" = invalid ]; then
        printf 'valid\nNot A Token\n' >"$tree/git/hooks/agent-tokens"
    elif [ "$case" = crlf ]; then
        printf 'valid\r\n' >"$tree/git/hooks/agent-tokens"
    fi
    if run_hook "$tree/codex/hooks/no_ai_attribution_bash.py" "$ATTR_GEN_PAYLOAD" &&
        grep -q 'attribution check skipped\.$' /tmp/codex-hook-test.err; then
        printf 'PASS  %s\n' "attribution bash: skips with a warning when agent-tokens is $case"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "attribution bash: skips with a warning when agent-tokens is $case" >&2
        FAIL=$((FAIL + 1))
    fi
    rm -rf "$tree"
done

assert_allows "allows tool mentions in markdown" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"notes.md\",\"content\":\"Generated by ${ATTRIBUTION_SUBJECT} is a forbidden phrase.\\n\"}}"

assert_blocks "blocks emoji in Write content" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"claude/rules/example.md","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"codex/hooks/block_secrets.py"}}'

# Exercise the shared guard with both harness envelopes, without running Herd.
for payload in \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create task"}}' \
    '{"tool_name":"exec_command","tool_input":{"cmd":"herdr worktree create task"}}' \
    '{"toolName":"shell_command","toolInput":{"command":"herdr worktree create task"}}' \
    '{"tool_name":"unified_exec","tool_input":{"args":{"cmd":"herdr worktree create task"}}}'; do
    if run_hook claude/hooks/herdr_worktree_guard.py "$payload"; then
        hook_status=0
    else
        hook_status=$?
    fi
    if [ "$hook_status" -eq 2 ]; then
        printf 'PASS  Herd guard rejects shell envelope\n'
        PASS=$((PASS + 1))
    else
        printf 'FAIL  Herd guard returned %s instead of 2\n' "$hook_status"
        FAIL=$((FAIL + 1))
    fi
done

assert_allows "Herd guard permits an explicit repository" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"herdr worktree create task --cwd /tmp/repo"}}'
assert_allows "Herd guard ignores a non-shell tool" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"Write","tool_input":{"command":"herdr worktree create task"}}'
assert_allows "Herd guard ignores malformed input" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"exec_command","tool_input":null}'

# Pass command strings only to the shared rm guard; none are executed.
assert_denies_2 "rm guard blocks Claude Bash root deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"Bash","cwd":"/tmp/project","tool_input":{"command":"rm -rf /"}}'
assert_denies_2 "rm guard blocks Codex root glob from tool workdir" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","cwd":"/tmp/project","tool_input":{"cmd":"rm -rf *","workdir":"/"}}'
assert_denies_2 "rm guard blocks camelCase shell home glob" \
    claude/hooks/rm_guard.py \
    '{"toolName":"shell_command","toolInput":{"command":"rm -rf ~/*"}}'
assert_denies_2 "rm guard blocks nested unified exec git deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"unified_exec","tool_input":{"args":{"cmd":"rm -rf .git","workdir":"/tmp/project"}}}'
assert_denies_2 "rm guard blocks nested shell command git deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"shell","tool_input":{"args":{"command":"rm -rf .git"}}}'
assert_allows "rm guard permits disposable tmp cleanup" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"rm -rf /tmp/rm-guard-disposable"}}'
assert_allows "rm guard ignores a non-shell tool" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"Write","tool_input":{"command":"rm -rf /"}}'
assert_allows "rm guard ignores malformed shell input" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","tool_input":{"args":[]}}'

# Planning-artifact guard through the Codex payload shapes. A literal
# protected pathspec denies without a resolvable repository (the cwd must
# never be a real checkout, or the temp-root exemption could flip the deny);
# an unrelated path allows.
assert_denies_2 "planning guard blocks Codex exec_command spec add" \
    claude/hooks/planning_artifact_guard.py \
    '{"tool_name":"exec_command","cwd":"/nonexistent-planning-guard/project","tool_input":{"cmd":"git add docs/specs/x.md"}}'
assert_denies_2 "planning guard blocks nested unified_exec contract add" \
    claude/hooks/planning_artifact_guard.py \
    '{"tool_name":"unified_exec","tool_input":{"args":{"cmd":"git add -f claude/contracts/x.json","workdir":"/nonexistent-planning-guard/project"}}}'
assert_allows "planning guard allows an unrelated Codex add" \
    claude/hooks/planning_artifact_guard.py \
    '{"tool_name":"shell_command","cwd":"/nonexistent-planning-guard/project","tool_input":{"command":"git add README.md"}}'
assert_allows "planning guard ignores a non-shell tool" \
    claude/hooks/planning_artifact_guard.py \
    '{"tool_name":"Write","tool_input":{"command":"git add docs/specs/x.md"}}'

if python3 - <<'PY'
import importlib.util

spec = importlib.util.spec_from_file_location("adapter", "codex/hooks/orch_edit_guard.py")
adapter = importlib.util.module_from_spec(spec)
spec.loader.exec_module(adapter)
thread = "11111111-1111-1111-1111-111111111111"
shell = adapter.normalize({"tool_name": "exec_command", "thread_id": thread,
                           "tool_input": {"cmd": "echo x > tracked.txt", "workdir": "/repo"}})
assert shell["tool_name"] == "Bash" and shell["session_id"] == thread
assert shell["cwd"] == "/repo" and shell["tool_input"]["command"] == "echo x > tracked.txt"
shell_args = adapter.normalize({"tool_name": "unified_exec", "thread_id": thread,
                                "tool_input": {"args": {"cmd": "echo x > tracked.txt", "workdir": "/nested"}}})
assert shell_args["cwd"] == "/nested"
patch = adapter.normalize({"tool_name": "apply_patch", "thread_id": thread,
                           "tool_input": {"input": "*** Update File: [id].txt\n*** Move to: $name.txt\n"}})
assert patch["tool_name"] == "Write" and patch["tool_input"]["file_paths"] == ["[id].txt", "$name.txt"]
PY
then
    printf 'PASS  Codex adapter normalizes exec_command and apply_patch payloads\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  Codex adapter normalizes exec_command and apply_patch payloads\n' >&2
    FAIL=$((FAIL + 1))
fi

if python3 - <<'PY'
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

root = Path.cwd()
adapter = root / "codex/hooks/orch_edit_guard.py"
core = root / "claude/hooks/herdr_orch_core.py"
session = "33333333-3333-3333-3333-333333333333"
fixture = Path(tempfile.mkdtemp(prefix="codex-orch-edit-"))
try:
    home = fixture / "home"
    repo = home / "Git/work/repo"
    personal_repo = home / "Git/personal/repo"
    repo.mkdir(parents=True)
    personal_repo.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", "--initial-branch=main", repo], check=True)
    (repo / "tracked.txt").write_text("tracked\n")
    (repo / "scratch/.todos").mkdir(parents=True)
    (repo / "scratch/.todos/task.txt").write_text("scratch\n")
    subprocess.run(["git", "-C", repo, "add", "tracked.txt", "scratch/.todos/task.txt"], check=True)
    subprocess.run(["git", "-C", repo, "-c", "user.name=t", "-c", "user.email=t@x", "commit", "-qm", "base"], check=True)
    subprocess.run(["git", "-C", repo, "remote", "add", "origin", "git@example.com:org/codex-work.git"], check=True)
    subprocess.run(["git", "init", "-q", "--initial-branch=main", personal_repo], check=True)
    (personal_repo / "tracked.txt").write_text("personal\n")
    subprocess.run(["git", "-C", personal_repo, "add", "tracked.txt"], check=True)
    subprocess.run(["git", "-C", personal_repo, "-c", "user.name=t", "-c", "user.email=t@x", "commit", "-qm", "base"], check=True)
    subprocess.run(["git", "-C", personal_repo, "remote", "add", "origin", "git@example.com:org/codex-personal.git"], check=True)
    env = dict(os.environ, HOME=str(home), CLAUDE_WORK_TREE=str(home / "Git/work"),
               CLAUDE_WORK_CONFIG_DIR=str(home / ".claude-work"), CODEX_HOME=str(home / ".codex"),
               HERDR_COORDINATION_ROOT=str(fixture / "coordination"), HERDR_ENV="1",
               PYTHONDONTWRITEBYTECODE="1")
    env.pop("CLAUDE_CONFIG_DIR", None)
    remote = subprocess.check_output(["git", "-C", repo, "remote", "get-url", "origin"], text=True).strip()
    slug = subprocess.check_output([sys.executable, "-c", "import sys; sys.path.insert(0, 'claude/hooks'); import herdr_orch_core as c; print(c.repo_slug(sys.argv[1]))", remote], text=True, cwd=root).strip()
    fence = subprocess.check_output([sys.executable, core, "claim-owner", "--repo-path", repo,
                                    "--repo-slug", slug, "--runtime", "codex",
                                    "--session", session, "--thread-id", session, "--host", "h", "--pid", "1",
                                    "--stale-secs", "0"], text=True, env=env).strip()
    assert fence == "1", fence
    payload = {"tool_name": "unified_exec", "thread_id": session,
               "tool_input": {"args": {"cmd": "echo x > tracked.txt", "workdir": str(repo)}}}
    denied = subprocess.run([sys.executable, adapter], input=json.dumps(payload), text=True, capture_output=True, env=env)
    assert denied.returncode == 2, (denied.returncode, denied.stdout, denied.stderr)
    foreign = {"tool_name": "exec_command", "thread_id": session, "cwd": str(repo),
               "tool_input": {"cmd": "echo x > tracked.txt", "workdir": str(personal_repo)}}
    foreign_denied = subprocess.run([sys.executable, adapter], input=json.dumps(foreign), text=True, capture_output=True, env=env)
    assert foreign_denied.returncode == 2, (foreign_denied.returncode, foreign_denied.stdout, foreign_denied.stderr)
    assert "does not orchestrate" in foreign_denied.stdout, foreign_denied.stdout
    personal_env = dict(env, HERDR_PERSONAL="1")
    personal_remote = subprocess.check_output(["git", "-C", personal_repo, "remote", "get-url", "origin"], text=True).strip()
    personal_slug = subprocess.check_output([sys.executable, "-c", "import sys; sys.path.insert(0, 'claude/hooks'); import herdr_orch_core as c; print(c.repo_slug(sys.argv[1]))", personal_remote], text=True, cwd=root).strip()
    personal_fence = subprocess.check_output([sys.executable, core, "claim-owner", "--repo-path", personal_repo,
                                               "--repo-slug", personal_slug, "--runtime", "codex",
                                               "--session", session, "--thread-id", session, "--host", "h", "--pid", "1",
                                               "--stale-secs", "0"], text=True, env=personal_env).strip()
    assert personal_fence == "1", personal_fence
    override_denied = subprocess.run([sys.executable, adapter], input=json.dumps(foreign), text=True, capture_output=True, env=personal_env)
    assert override_denied.returncode == 2, (override_denied.returncode, override_denied.stdout, override_denied.stderr)
    assert "does not orchestrate" not in override_denied.stdout, override_denied.stdout
    subprocess.run([sys.executable, core, "allow-edit", "--repo-path", repo, "--repo-slug", slug,
                    "--runtime", "codex", "--session", session, "--fence", "1", "--minutes", "5",
                    "--max-edits", "1", "--note", "move"], check=True, env=env, capture_output=True, text=True)
    move = {"tool_name": "apply_patch", "thread_id": session, "cwd": str(repo),
            "tool_input": {"input": "*** Update File: scratch/.todos/task.txt\n*** Move to: tracked.txt\n"}}
    allowed = subprocess.run([sys.executable, adapter], input=json.dumps(move), text=True, capture_output=True, env=env)
    exhausted = subprocess.run([sys.executable, adapter], input=json.dumps(move), text=True, capture_output=True, env=env)
    assert allowed.returncode == 0, (allowed.returncode, allowed.stdout, allowed.stderr)
    assert exhausted.returncode == 2, (exhausted.returncode, exhausted.stdout, exhausted.stderr)
finally:
    shutil.rmtree(fixture)
PY
then
    printf 'PASS  Codex adapter enforces a work-account owner and apply_patch budget\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  Codex adapter enforces a work-account owner and apply_patch budget\n' >&2
    FAIL=$((FAIL + 1))
fi

HERDR_ENV=1 assert_denies_2 "git guard blocks global metadata writes from Codex" \
    claude/hooks/git_remote_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"git config --global core.editor false"}}'
HERDR_ENV=1 assert_denies_2 "git guard handles nested camelCase shell input" \
    claude/hooks/git_remote_guard.py \
    '{"toolName":"unified_exec","toolInput":{"args":{"command":"git config --global core.editor false"}}}'
HERDR_ENV=1 assert_denies_2 "git guard blocks apply_patch metadata writes" \
    claude/hooks/git_remote_guard.py \
    '{"tool_name":"apply_patch","tool_input":{"input":"*** Begin Patch\n*** Update File: /guard-fixture/.git/config\n@@\n-old\n+new\n*** End Patch"}}'
HERDR_ENV=0 assert_allows "git guard stays inactive outside Herd" \
    claude/hooks/git_remote_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"git config --global core.editor false"}}'

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
