#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/codex-hook-test.out 2>/tmp/codex-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_blocks "blocks attribution in Write content" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\nprint(1)\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"codex/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_allows "allows tool mentions in markdown" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"notes.md\",\"content\":\"Generated by ${ATTRIBUTION_SUBJECT} is a forbidden phrase.\\n\"}}"

assert_blocks "blocks emoji in Write content" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"claude/rules/example.md","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"codex/hooks/block_secrets.py"}}'

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
