#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/codex-hook-test.out 2>/tmp/codex-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_denies_2() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        hook_status=0
    else
        hook_status=$?
    fi
    if [ "$hook_status" -eq 2 ]; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s returned %s instead of 2\n' "$label" "$hook_status" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_blocks "blocks attribution in Write content" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\nprint(1)\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"codex/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_allows "allows tool mentions in markdown" \
    codex/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"notes.md\",\"content\":\"Generated by ${ATTRIBUTION_SUBJECT} is a forbidden phrase.\\n\"}}"

assert_blocks "blocks emoji in Write content" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    codex/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"claude/rules/example.md","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    codex/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"codex/hooks/block_secrets.py"}}'

# Exercise the shared guard with both harness envelopes, without running Herd.
for payload in \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create task"}}' \
    '{"tool_name":"exec_command","tool_input":{"cmd":"herdr worktree create task"}}' \
    '{"toolName":"shell_command","toolInput":{"command":"herdr worktree create task"}}' \
    '{"tool_name":"unified_exec","tool_input":{"args":{"cmd":"herdr worktree create task"}}}'; do
    if run_hook claude/hooks/herdr_worktree_guard.py "$payload"; then
        hook_status=0
    else
        hook_status=$?
    fi
    if [ "$hook_status" -eq 2 ]; then
        printf 'PASS  Herd guard rejects shell envelope\n'
        PASS=$((PASS + 1))
    else
        printf 'FAIL  Herd guard returned %s instead of 2\n' "$hook_status"
        FAIL=$((FAIL + 1))
    fi
done

assert_allows "Herd guard permits an explicit repository" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"herdr worktree create task --cwd /tmp/repo"}}'
assert_allows "Herd guard ignores a non-shell tool" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"Write","tool_input":{"command":"herdr worktree create task"}}'
assert_allows "Herd guard ignores malformed input" \
    claude/hooks/herdr_worktree_guard.py \
    '{"tool_name":"exec_command","tool_input":null}'

# Pass command strings only to the shared rm guard; none are executed.
assert_denies_2 "rm guard blocks Claude Bash root deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"Bash","cwd":"/tmp/project","tool_input":{"command":"rm -rf /"}}'
assert_denies_2 "rm guard blocks Codex root glob from tool workdir" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","cwd":"/tmp/project","tool_input":{"cmd":"rm -rf *","workdir":"/"}}'
assert_denies_2 "rm guard blocks camelCase shell home glob" \
    claude/hooks/rm_guard.py \
    '{"toolName":"shell_command","toolInput":{"command":"rm -rf ~/*"}}'
assert_denies_2 "rm guard blocks nested unified exec git deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"unified_exec","tool_input":{"args":{"cmd":"rm -rf .git","workdir":"/tmp/project"}}}'
assert_denies_2 "rm guard blocks nested shell command git deletion" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"shell","tool_input":{"args":{"command":"rm -rf .git"}}}'
assert_allows "rm guard permits disposable tmp cleanup" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","tool_input":{"cmd":"rm -rf /tmp/rm-guard-disposable"}}'
assert_allows "rm guard ignores a non-shell tool" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"Write","tool_input":{"command":"rm -rf /"}}'
assert_allows "rm guard ignores malformed shell input" \
    claude/hooks/rm_guard.py \
    '{"tool_name":"exec_command","tool_input":{"args":[]}}'

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
