#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

# account_guard.py never changes exit status (always 0); it signals by emitting
# a JSON warning on stdout or staying silent. guard_case drives it against a
# fixture HOME so the account-aware routing is deterministic and machine-state
# independent.
#   label expect(warn|silent) home cfg(empty=unset CLAUDE_CONFIG_DIR) cwd
guard_case() {
    label="$1"
    expect="$2"
    ghome="$3"
    gcfg="$4"
    gcwd="$5"
    payload=$(printf '{"cwd":"%s"}' "$gcwd")
    if [ -n "$gcfg" ]; then
        out=$(printf '%s' "$payload" | env \
            HOME="$ghome" \
            CLAUDE_CONFIG_DIR="$gcfg" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    else
        out=$(printf '%s' "$payload" | env -u CLAUDE_CONFIG_DIR \
            HOME="$ghome" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    fi
    if [ "$expect" = warn ]; then
        if printf '%s' "$out" | grep -q 'account_guard'; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected a warning, got silence)\n' "$label" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        if [ -z "$out" ]; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected silence, got: %s)\n' "$label" "$out" >&2
            FAIL=$((FAIL + 1))
        fi
    fi
}

assert_blocks "blocks attribution in code content" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"claude/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_blocks "blocks emoji in code content" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"codex/rules/example.rules","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"claude/hooks/block_secrets.py"}}'

# push_guard.py: exit 2 (block) on history-rewriting pushes, 0 otherwise.
assert_blocks "blocks git push --force" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force origin main"}}'
assert_blocks "blocks git push -f" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -f"}}'
assert_blocks "blocks git push --force-with-lease" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force-with-lease"}}'
assert_blocks "blocks trailing force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main --force"}}'
assert_blocks "blocks bundled short force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -fu origin main"}}'
assert_blocks "blocks quoted force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push \"--force\" origin main"}}'
assert_blocks "blocks forced refspec" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin +main"}}'
assert_blocks "blocks git push --mirror" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --mirror origin"}}'
assert_blocks "blocks force push in compound command" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git fetch origin && git push --force-with-lease"}}'
assert_blocks "blocks force push wrapped in sh -c" \
    claude/hooks/push_guard.py \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"sh -c 'git push --force'\"}}"
assert_blocks "blocks path-qualified git force push" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"/usr/bin/git push -f origin main"}}'
assert_blocks "blocks override hidden in unrelated env value" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"FOO=DOTFILES_ALLOW_FORCE_PUSH=1 git push origin main --force"}}'
assert_allows "allows plain git push" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -u origin main"}}'
assert_allows "allows force flag in non-push segment" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main && rm -f /tmp/x"}}'
assert_allows "allows force flag in newline-separated segment" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main\nrm -f /tmp/x"}}'
assert_allows "allows non-push git command with -f" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git checkout push-fix -f"}}'
assert_allows "allows force mention in commit message" \
    claude/hooks/push_guard.py \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m 'never push --force to main'\"}}"
assert_allows "allows non-git command" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"rsync --force a b"}}'
assert_allows "allows non-Bash tool" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}'
assert_allows "allows override prefix after user confirmation" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"DOTFILES_ALLOW_FORCE_PUSH=1 git push --force-with-lease"}}'

# herdr_worktree_guard.py: exit 2 (block) on `herdr worktree create` lacking
# --cwd, 0 otherwise. `worktree open` is out of scope and never blocked.
HWG=claude/hooks/herdr_worktree_guard.py
assert_blocks "hwg: blocks bare worktree create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create"}}'
assert_blocks "hwg: blocks create with other flags but no --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --label y"}}'
assert_blocks "hwg: blocks backslash-continued create with no --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create \\\n  --branch x \\\n  --label y"}}'
assert_blocks "hwg: blocks create whose --cwd is only in a comment" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x # --cwd /repo"}}'
assert_blocks "hwg: blocks create in compound command" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"cd /r && herdr worktree create --branch x"}}'
assert_blocks "hwg: blocks create when --cwd is in a different segment" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x; echo --cwd /r"}}'
assert_blocks "hwg: blocks create when --cwd is on a different line" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x\necho --cwd /r"}}'
assert_blocks "hwg: blocks create wrapped in sh -c" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"sh -c 'herdr worktree create --branch x'\"}}"
assert_blocks "hwg: blocks path-qualified herdr create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"/opt/homebrew/bin/herdr worktree create"}}'
assert_blocks "hwg: blocks env-assignment-prefixed create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"HERDR_ENV=1 herdr worktree create"}}'
assert_blocks "hwg: blocks create when a mid-token # precedes it (real bash does not treat this as a comment)" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"FOO=a#b herdr worktree create --branch x"}}'
assert_allows "hwg: allows create with --cwd when a flag value contains a mid-token #" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --label abc#def --cwd /repo"}}'
assert_blocks "hwg: blocks env-wrapped create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"env HERDR_ENV=1 herdr worktree create"}}'
assert_blocks "hwg: blocks command-wrapped create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"command herdr worktree create"}}'
assert_blocks "hwg: blocks create after herdr global option" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr --session main worktree create --branch x"}}'
assert_allows "hwg: allows create with --cwd first" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd /repo --branch x"}}'
assert_allows "hwg: allows create with --cwd=value" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd=/repo"}}'
assert_allows "hwg: allows create with --cwd last" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --cwd /repo"}}'
assert_allows "hwg: allows quoted substitution as --cwd value" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd \"$(git rev-parse --show-toplevel)\""}}'
assert_allows "hwg: allows quoted separator inside an argument" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"herdr worktree create --label 'a;b' --cwd /repo\"}}"
assert_allows "hwg: allows global option plus --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr --session main worktree create --cwd /repo"}}'
assert_allows "hwg: allows backslash-continued create with --cwd on line 2" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create \\\n  --cwd /repo"}}'
assert_allows "hwg: allows redirection and pipe after a valid create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd /repo 2>&1 | tee log"}}'
assert_allows "hwg: allows worktree open without --cwd (out of scope)" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree open --workspace ws1"}}'
assert_allows "hwg: allows worktree list" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree list"}}'
assert_allows "hwg: allows worktree remove" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree remove --workspace ws1"}}'
assert_allows "hwg: allows mention in commit message" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"docs: mention herdr worktree create\""}}'
assert_allows "hwg: allows mention in grep pattern" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"grep -rn \"herdr worktree create\" claude/"}}'
assert_allows "hwg: allows mention behind a prefix wrapper" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"env echo 'herdr worktree create'\"}}"
assert_allows "hwg: allows non-Bash tool" \
    "$HWG" \
    '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}'
assert_allows "hwg: allows payload with no tool_input (fail open)" \
    "$HWG" \
    '{"tool_name":"Bash"}'

# Exact contract: deny is exit 2 with the fix-naming first line; allow is
# exit 0 and silent. (assert_blocks accepts any nonzero status.)
if printf '%s\n' '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x"}}' \
        | "$HWG" >/dev/null 2>/tmp/claude-hook-test.err; then
    hwg_rc=0
else
    hwg_rc=$?
fi
if [ "$hwg_rc" = 2 ] && head -n 1 /tmp/claude-hook-test.err \
        | grep -q '^Blocked: herdr worktree create without --cwd'; then
    printf 'PASS  hwg: deny is exit 2 with fix-naming message\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: deny is exit 2 with fix-naming message (rc=%s)\n' "$hwg_rc" >&2
    FAIL=$((FAIL + 1))
fi
if printf '%s\n' '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --cwd /repo"}}' \
        | "$HWG" >/dev/null 2>/tmp/claude-hook-test.err \
        && [ ! -s /tmp/claude-hook-test.err ]; then
    printf 'PASS  hwg: allow is exit 0 and silent\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: allow is exit 0 and silent\n' >&2
    FAIL=$((FAIL + 1))
fi

# Static registration: the template's PreToolUse Bash group must list the
# guards in this exact order (the new guard last, after push_guard).
# Independent of live machine state; the live drift check below is derived
# from the template and covers reconciled machines.
if python3 - <<'PY'
import json
import sys

tmpl = json.load(open("claude/settings.json.tmpl"))["hooks"]["PreToolUse"]
cmds = [h["command"] for e in tmpl if e.get("matcher") == "Bash" for h in e["hooks"]]
want = [
    "~/.claude/hooks/commit_guard.py",
    "~/.claude/hooks/no_ai_attribution_bash.py",
    "~/.claude/hooks/push_guard.py",
    "~/.claude/hooks/herdr_worktree_guard.py",
]
sys.exit(0 if cmds == want else 1)
PY
then
    printf 'PASS  hwg: template lists the Bash guards in order, worktree guard last\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: template lists the Bash guards in order, worktree guard last\n' >&2
    FAIL=$((FAIL + 1))
fi

# account_guard.py account-aware routing. Fixtures use synthetic account tokens
# in throwaway HOMEs -- no real credentials, no employer strings.
GUARD_FIX=$(mktemp -d)
trap 'rm -rf "$GUARD_FIX"' EXIT

# Fixture A: the default ~/.claude dir is signed into the WORK account (the
# IDE-launch machine that produced the original false positive). Work identity
# lives in the home-root ~/.claude.json legacy fallback.
mkdir -p "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/.claude" \
    "$GUARD_FIX/a/Git/work/repo" "$GUARD_FIX/a/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude.json"

guard_case "guard: IDE launch, work account on work repo -> silent (false positive fixed)" \
    silent "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/work/repo"
guard_case "guard: IDE launch, work account on personal repo -> warn (blind spot caught)" \
    warn "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/personal/repo"
guard_case "guard: wrapper launch, work dir on work repo -> silent" \
    silent "$GUARD_FIX/a" "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/Git/work/repo"

# Fixture B: clean separation -- default ~/.claude signed into a personal
# account, ~/.claude-work into the work account.
mkdir -p "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/.claude" \
    "$GUARD_FIX/b/Git/work/repo" "$GUARD_FIX/b/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/b/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"personal-uuid"}}' > "$GUARD_FIX/b/.claude.json"

guard_case "guard: personal account on personal repo -> silent" \
    silent "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/personal/repo"
guard_case "guard: personal account on work repo -> warn" \
    warn "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/work/repo"
guard_case "guard: wrapper launch, work account on work repo -> silent" \
    silent "$GUARD_FIX/b" "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/Git/work/repo"

# Fixture C: no work login at all (cloud container / personal-only machine).
# Account cannot be resolved -> falls back to the original path-based check.
mkdir -p "$GUARD_FIX/c/.claude" \
    "$GUARD_FIX/c/Git/work/repo" "$GUARD_FIX/c/Git/personal/repo"

guard_case "guard: fallback path check, default dir on work repo -> warn" \
    warn "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/work/repo"
guard_case "guard: fallback path check, default dir on personal repo -> silent" \
    silent "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/personal/repo"

# Settings drift: hand-merged machines that missed a SessionStart hook
# entry must fail visibly instead of silently lacking the account-mismatch
# guard. Both account config dirs carry their own machine-local settings.json
# (~/.claude personal, ~/.claude-work work); check every one that exists.
# Skipped when no live settings file exists (fresh machine or CI).
for settings_dir in "$HOME/.claude" "$HOME/.claude-work"; do
    if [ -f "$settings_dir/settings.json" ]; then
        # Every hook command the template registers, for every event, must be
        # registered live. Derived from the template so a new hook can never
        # be invisible to this check.
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

live = json.load(open(os.environ["SETTINGS_PATH"])).get("hooks", {})
tmpl = json.load(open("claude/settings.json.tmpl")).get("hooks", {})
missing = []
for event, entries in tmpl.items():
    wanted = [h.get("command", "") for e in entries for h in e.get("hooks", [])]
    got = [h.get("command", "") for e in live.get(event, []) for h in e.get("hooks", [])]
    for cmd in wanted:
        if cmd not in got:
            missing.append(event + ": " + cmd)
for entry in missing:
    print("  missing hook: " + entry)
sys.exit(1 if missing else 0)
PY
        then
            printf 'PASS  settings: %s registers every template hook\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s missing template hooks (run update to reconcile)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi

        # Permissions drift: the reconcile treats permissions as a
        # template-owned key (reasserted wholesale on every update), so live
        # permissions must equal the template's. A mismatch means the machine
        # missed an update and may silently retain retired broad grants.
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

live = json.load(open(os.environ["SETTINGS_PATH"])).get("permissions") or {}
tmpl = json.load(open("claude/settings.json.tmpl")).get("permissions") or {}
if live == tmpl:
    sys.exit(0)
for key in sorted(set(live) | set(tmpl)):
    lv, tv = live.get(key), tmpl.get(key)
    if lv == tv:
        continue
    if isinstance(lv, list) and isinstance(tv, list):
        for rule in sorted(set(lv) - set(tv)):
            print("  " + key + " live-only rule: " + rule)
        for rule in sorted(set(tv) - set(lv)):
            print("  " + key + " missing rule:   " + rule)
    else:
        print("  " + key + ": live=" + repr(lv) + " template=" + repr(tv))
sys.exit(1)
PY
        then
            printf 'PASS  settings: %s permissions match template\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s permissions drifted (update reconciles: template rules reassert, live-only grants are DROPPED -- commit intentional grants to the template)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        printf 'SKIP  settings: no live %s/settings.json\n' "$settings_dir"
    fi
done

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
