#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

# account_guard.py never changes exit status (always 0); it signals by emitting
# a JSON warning on stdout or staying silent. guard_case drives it against a
# fixture HOME so the account-aware routing is deterministic and machine-state
# independent.
#   label expect(warn|silent) home cfg(empty=unset CLAUDE_CONFIG_DIR) cwd
guard_case() {
    label="$1"
    expect="$2"
    ghome="$3"
    gcfg="$4"
    gcwd="$5"
    payload=$(printf '{"cwd":"%s"}' "$gcwd")
    if [ -n "$gcfg" ]; then
        out=$(printf '%s' "$payload" | env \
            HOME="$ghome" \
            CLAUDE_CONFIG_DIR="$gcfg" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    else
        out=$(printf '%s' "$payload" | env -u CLAUDE_CONFIG_DIR \
            HOME="$ghome" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    fi
    if [ "$expect" = warn ]; then
        if printf '%s' "$out" | grep -q 'account_guard'; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected a warning, got silence)\n' "$label" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        if [ -z "$out" ]; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected silence, got: %s)\n' "$label" "$out" >&2
            FAIL=$((FAIL + 1))
        fi
    fi
}

assert_blocks "blocks attribution in code content" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"claude/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_blocks "blocks emoji in code content" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"codex/rules/example.rules","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"claude/hooks/block_secrets.py"}}'

# push_guard.py signals via JSON permissionDecision "ask" on stdout (exit 0
# either way), so assert on the output, not the exit code.
assert_asks() {
    label="$1"
    payload="$2"
    out=$(printf '%s\n' "$payload" | claude/hooks/push_guard.py 2>/dev/null)
    if printf '%s' "$out" | grep -q '"permissionDecision": "ask"'; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s (expected ask decision, got: %s)\n' "$label" "$out" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_no_ask() {
    label="$1"
    payload="$2"
    out=$(printf '%s\n' "$payload" | claude/hooks/push_guard.py 2>/dev/null)
    if [ -z "$out" ]; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s (expected silence, got: %s)\n' "$label" "$out" >&2
        FAIL=$((FAIL + 1))
    fi
}

assert_asks "asks on git push --force" \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force origin main"}}'
assert_asks "asks on git push -f" \
    '{"tool_name":"Bash","tool_input":{"command":"git push -f"}}'
assert_asks "asks on git push --force-with-lease" \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force-with-lease"}}'
assert_asks "asks on trailing force flag" \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main --force"}}'
assert_asks "asks on forced refspec" \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin +main"}}'
assert_asks "asks on force push in compound command" \
    '{"tool_name":"Bash","tool_input":{"command":"git fetch origin && git push --force-with-lease"}}'
assert_no_ask "silent on plain git push" \
    '{"tool_name":"Bash","tool_input":{"command":"git push -u origin main"}}'
assert_no_ask "silent on force flag in non-push segment" \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main && rm -f /tmp/x"}}'
assert_no_ask "silent on non-git command" \
    '{"tool_name":"Bash","tool_input":{"command":"rsync --force a b"}}'
assert_no_ask "silent on non-Bash tool" \
    '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}'

# account_guard.py account-aware routing. Fixtures use synthetic account tokens
# in throwaway HOMEs -- no real credentials, no employer strings.
GUARD_FIX=$(mktemp -d)
trap 'rm -rf "$GUARD_FIX"' EXIT

# Fixture A: the default ~/.claude dir is signed into the WORK account (the
# IDE-launch machine that produced the original false positive). Work identity
# lives in the home-root ~/.claude.json legacy fallback.
mkdir -p "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/.claude" \
    "$GUARD_FIX/a/Git/work/repo" "$GUARD_FIX/a/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude.json"

guard_case "guard: IDE launch, work account on work repo -> silent (false positive fixed)" \
    silent "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/work/repo"
guard_case "guard: IDE launch, work account on personal repo -> warn (blind spot caught)" \
    warn "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/personal/repo"
guard_case "guard: wrapper launch, work dir on work repo -> silent" \
    silent "$GUARD_FIX/a" "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/Git/work/repo"

# Fixture B: clean separation -- default ~/.claude signed into a personal
# account, ~/.claude-work into the work account.
mkdir -p "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/.claude" \
    "$GUARD_FIX/b/Git/work/repo" "$GUARD_FIX/b/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/b/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"personal-uuid"}}' > "$GUARD_FIX/b/.claude.json"

guard_case "guard: personal account on personal repo -> silent" \
    silent "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/personal/repo"
guard_case "guard: personal account on work repo -> warn" \
    warn "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/work/repo"
guard_case "guard: wrapper launch, work account on work repo -> silent" \
    silent "$GUARD_FIX/b" "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/Git/work/repo"

# Fixture C: no work login at all (cloud container / personal-only machine).
# Account cannot be resolved -> falls back to the original path-based check.
mkdir -p "$GUARD_FIX/c/.claude" \
    "$GUARD_FIX/c/Git/work/repo" "$GUARD_FIX/c/Git/personal/repo"

guard_case "guard: fallback path check, default dir on work repo -> warn" \
    warn "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/work/repo"
guard_case "guard: fallback path check, default dir on personal repo -> silent" \
    silent "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/personal/repo"

# Settings drift: hand-merged machines that missed a SessionStart hook
# entry must fail visibly instead of silently lacking the account-mismatch
# guard. Both account config dirs carry their own machine-local settings.json
# (~/.claude personal, ~/.claude-work work); check every one that exists.
# Skipped when no live settings file exists (fresh machine or CI).
for settings_dir in "$HOME/.claude" "$HOME/.claude-work"; do
    if [ -f "$settings_dir/settings.json" ]; then
        for required_hook in account_guard.py; do
            if SETTINGS_PATH="$settings_dir/settings.json" REQUIRED_HOOK="$required_hook" python3 - <<'PY'
import json
import os
import sys

cfg = json.load(open(os.environ["SETTINGS_PATH"]))
required = os.environ["REQUIRED_HOOK"]
entries = cfg.get("hooks", {}).get("SessionStart", [])
cmds = [h.get("command", "") for e in entries for h in e.get("hooks", [])]
sys.exit(0 if any(c.endswith("hooks/" + required) for c in cmds) else 1)
PY
            then
                printf 'PASS  settings: %s SessionStart hooks register %s\n' "$settings_dir" "$required_hook"
                PASS=$((PASS + 1))
            else
                printf 'FAIL  settings: %s SessionStart hooks missing %s (hand-merge required)\n' "$settings_dir" "$required_hook" >&2
                FAIL=$((FAIL + 1))
            fi
        done

        for required_hook in commit_guard.py no_ai_attribution_bash.py push_guard.py; do
            if SETTINGS_PATH="$settings_dir/settings.json" REQUIRED_HOOK="$required_hook" python3 - <<'PY'
import json
import os
import sys

cfg = json.load(open(os.environ["SETTINGS_PATH"]))
required = os.environ["REQUIRED_HOOK"]
entries = cfg.get("hooks", {}).get("PreToolUse", [])
cmds = [h.get("command", "") for e in entries for h in e.get("hooks", [])]
sys.exit(0 if any(c.endswith("hooks/" + required) for c in cmds) else 1)
PY
            then
                printf 'PASS  settings: %s PreToolUse hooks register %s\n' "$settings_dir" "$required_hook"
                PASS=$((PASS + 1))
            else
                printf 'FAIL  settings: %s PreToolUse hooks missing %s (run update to reconcile)\n' "$settings_dir" "$required_hook" >&2
                FAIL=$((FAIL + 1))
            fi
        done

        # Permissions drift: the reconcile treats permissions as a
        # template-owned key (reasserted wholesale on every update), so live
        # permissions must equal the template's. A mismatch means the machine
        # missed an update and may silently retain retired broad grants.
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

live = json.load(open(os.environ["SETTINGS_PATH"])).get("permissions")
tmpl = json.load(open("claude/settings.json.tmpl")).get("permissions")
if live == tmpl:
    sys.exit(0)
live_allow = set((live or {}).get("allow", []))
tmpl_allow = set((tmpl or {}).get("allow", []))
for rule in sorted(live_allow - tmpl_allow):
    print("  live-only rule: " + rule)
for rule in sorted(tmpl_allow - live_allow):
    print("  missing rule:   " + rule)
sys.exit(1)
PY
        then
            printf 'PASS  settings: %s permissions match template\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s permissions drifted from template (run update to reconcile)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        printf 'SKIP  settings: no live %s/settings.json\n' "$settings_dir"
    fi
done

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
