#!/bin/sh
set -e

PASS=0
FAIL=0
ATTRIBUTION_SUBJECT="A""I"

run_hook() {
    hook="$1"
    payload="$2"
    printf '%s\n' "$payload" | "$hook" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err
}

assert_blocks() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}

assert_allows() {
    label="$1"
    hook="$2"
    payload="$3"
    if run_hook "$hook" "$payload"; then
        printf 'PASS  %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

# account_guard.py never changes exit status (always 0); it signals by emitting
# a JSON warning on stdout or staying silent. guard_case drives it against a
# fixture HOME so the account-aware routing is deterministic and machine-state
# independent.
#   label expect(warn|silent) home cfg(empty=unset CLAUDE_CONFIG_DIR) cwd
guard_case() {
    label="$1"
    expect="$2"
    ghome="$3"
    gcfg="$4"
    gcwd="$5"
    payload=$(printf '{"cwd":"%s"}' "$gcwd")
    if [ -n "$gcfg" ]; then
        out=$(printf '%s' "$payload" | env \
            HOME="$ghome" \
            CLAUDE_CONFIG_DIR="$gcfg" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    else
        out=$(printf '%s' "$payload" | env -u CLAUDE_CONFIG_DIR \
            HOME="$ghome" \
            CLAUDE_WORK_TREE="$ghome/Git/work" \
            CLAUDE_WORK_CONFIG_DIR="$ghome/.claude-work" \
            claude/hooks/account_guard.py 2>/dev/null)
    fi
    if [ "$expect" = warn ]; then
        if printf '%s' "$out" | grep -q 'account_guard'; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected a warning, got silence)\n' "$label" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        if [ -z "$out" ]; then
            printf 'PASS  %s\n' "$label"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  %s (expected silence, got: %s)\n' "$label" "$out" >&2
            FAIL=$((FAIL + 1))
        fi
    fi
}

assert_blocks "blocks attribution in code content" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"src/app.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_allows "allows attribution fixtures in workflow hooks" \
    claude/hooks/no_ai_comments.py \
    "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"claude/hooks/example.py\",\"content\":\"# Generated by ${ATTRIBUTION_SUBJECT}\\n\"}}"

assert_blocks "blocks emoji in code content" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"src/app.py","content":"print(\"hi \360\237\230\200\")"}}')"

assert_allows "allows emoji fixtures in workflow rules" \
    claude/hooks/emoji_guard.py \
    "$(printf '%b' '{"tool_name":"Write","tool_input":{"file_path":"codex/rules/example.rules","content":"fixture \360\237\230\200"}}')"

assert_blocks "blocks sensitive env file path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.local"}}'

assert_blocks "blocks secrets path segment" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"config/secrets/prod.json"}}'

assert_allows "allows env example path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":".env.example"}}'

assert_allows "allows public key path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"ssh/keys/id_ed25519_personal.pub"}}'

assert_allows "allows benign secret word in source name" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"src/secrets_manager/util.py"}}'

assert_allows "allows workflow hook secret checker path" \
    claude/hooks/block_secrets.py \
    '{"tool_name":"Read","tool_input":{"file_path":"claude/hooks/block_secrets.py"}}'

# push_guard.py: exit 2 (block) on history-rewriting pushes, 0 otherwise.
assert_blocks "blocks git push --force" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force origin main"}}'
assert_blocks "blocks git push -f" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -f"}}'
assert_blocks "blocks git push --force-with-lease" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --force-with-lease"}}'
assert_blocks "blocks trailing force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main --force"}}'
assert_blocks "blocks bundled short force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -fu origin main"}}'
assert_blocks "blocks quoted force flag" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push \"--force\" origin main"}}'
assert_blocks "blocks forced refspec" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin +main"}}'
assert_blocks "blocks git push --mirror" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push --mirror origin"}}'
assert_blocks "blocks force push in compound command" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git fetch origin && git push --force-with-lease"}}'
assert_blocks "blocks force push wrapped in sh -c" \
    claude/hooks/push_guard.py \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"sh -c 'git push --force'\"}}"
assert_blocks "blocks path-qualified git force push" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"/usr/bin/git push -f origin main"}}'
assert_blocks "blocks override hidden in unrelated env value" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"FOO=DOTFILES_ALLOW_FORCE_PUSH=1 git push origin main --force"}}'
assert_allows "allows plain git push" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push -u origin main"}}'
assert_allows "allows force flag in non-push segment" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main && rm -f /tmp/x"}}'
assert_allows "allows force flag in newline-separated segment" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git push origin main\nrm -f /tmp/x"}}'
assert_allows "allows non-push git command with -f" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"git checkout push-fix -f"}}'
assert_allows "allows force mention in commit message" \
    claude/hooks/push_guard.py \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"git commit -m 'never push --force to main'\"}}"
assert_allows "allows non-git command" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"rsync --force a b"}}'
assert_allows "allows non-Bash tool" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}'
assert_allows "allows override prefix after user confirmation" \
    claude/hooks/push_guard.py \
    '{"tool_name":"Bash","tool_input":{"command":"DOTFILES_ALLOW_FORCE_PUSH=1 git push --force-with-lease"}}'

# herdr_worktree_guard.py: exit 2 (block) on `herdr worktree create` lacking
# --cwd, 0 otherwise. `worktree open` is out of scope and never blocked.
HWG=claude/hooks/herdr_worktree_guard.py
assert_blocks "hwg: blocks bare worktree create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create"}}'
assert_blocks "hwg: blocks create with other flags but no --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --label y"}}'
assert_blocks "hwg: blocks backslash-continued create with no --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create \\\n  --branch x \\\n  --label y"}}'
assert_blocks "hwg: blocks create whose --cwd is only in a comment" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x # --cwd /repo"}}'
assert_blocks "hwg: blocks create in compound command" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"cd /r && herdr worktree create --branch x"}}'
assert_blocks "hwg: blocks create when --cwd is in a different segment" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x; echo --cwd /r"}}'
assert_blocks "hwg: blocks create when --cwd is on a different line" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x\necho --cwd /r"}}'
assert_blocks "hwg: blocks create wrapped in sh -c" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"sh -c 'herdr worktree create --branch x'\"}}"
assert_blocks "hwg: blocks path-qualified herdr create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"/opt/homebrew/bin/herdr worktree create"}}'
assert_blocks "hwg: blocks env-assignment-prefixed create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"HERDR_ENV=1 herdr worktree create"}}'
assert_blocks "hwg: blocks create when a mid-token # precedes it (real bash does not treat this as a comment)" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"FOO=a#b herdr worktree create --branch x"}}'
assert_allows "hwg: allows create with --cwd when a flag value contains a mid-token #" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --label abc#def --cwd /repo"}}'
assert_blocks "hwg: blocks create after --remote-keybindings global option" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr --remote-keybindings local worktree create --branch x"}}'
assert_blocks "hwg: blocks create wrapped in env -u VAR" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"env -u HERDR_CONFIG_PATH herdr worktree create --branch x"}}'
assert_allows "hwg: allows create wrapped in env -u VAR with --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"env -u HERDR_CONFIG_PATH herdr worktree create --branch x --cwd /repo"}}'
assert_allows "hwg: allows worktree create --help without --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --help"}}'
assert_blocks "hwg: blocks env-wrapped create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"env HERDR_ENV=1 herdr worktree create"}}'
assert_blocks "hwg: blocks command-wrapped create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"command herdr worktree create"}}'
assert_blocks "hwg: blocks create after herdr global option" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr --session main worktree create --branch x"}}'
assert_allows "hwg: allows create with --cwd first" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd /repo --branch x"}}'
assert_allows "hwg: allows create with --cwd=value" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd=/repo"}}'
assert_allows "hwg: allows create with --cwd last" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --cwd /repo"}}'
assert_allows "hwg: allows quoted substitution as --cwd value" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd \"$(git rev-parse --show-toplevel)\""}}'
assert_allows "hwg: allows quoted separator inside an argument" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"herdr worktree create --label 'a;b' --cwd /repo\"}}"
assert_allows "hwg: allows global option plus --cwd" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr --session main worktree create --cwd /repo"}}'
assert_allows "hwg: allows backslash-continued create with --cwd on line 2" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create \\\n  --cwd /repo"}}'
assert_allows "hwg: allows redirection and pipe after a valid create" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --cwd /repo 2>&1 | tee log"}}'
assert_allows "hwg: allows worktree open without --cwd (out of scope)" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree open --workspace ws1"}}'
assert_allows "hwg: allows worktree list" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree list"}}'
assert_allows "hwg: allows worktree remove" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"herdr worktree remove --workspace ws1"}}'
assert_allows "hwg: allows mention in commit message" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"docs: mention herdr worktree create\""}}'
assert_allows "hwg: allows mention in grep pattern" \
    "$HWG" \
    '{"tool_name":"Bash","tool_input":{"command":"grep -rn \"herdr worktree create\" claude/"}}'
assert_allows "hwg: allows mention behind a prefix wrapper" \
    "$HWG" \
    "{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"env echo 'herdr worktree create'\"}}"
assert_allows "hwg: allows non-Bash tool" \
    "$HWG" \
    '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}'
assert_allows "hwg: allows payload with no tool_input (fail open)" \
    "$HWG" \
    '{"tool_name":"Bash"}'

# Exact contract: deny is exit 2 with the fix-naming first line; allow is
# exit 0 and silent. (assert_blocks accepts any nonzero status.)
if printf '%s\n' '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x"}}' \
        | "$HWG" >/dev/null 2>/tmp/claude-hook-test.err; then
    hwg_rc=0
else
    hwg_rc=$?
fi
if [ "$hwg_rc" = 2 ] && head -n 1 /tmp/claude-hook-test.err \
        | grep -q '^Blocked: herdr worktree create without --cwd'; then
    printf 'PASS  hwg: deny is exit 2 with fix-naming message\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: deny is exit 2 with fix-naming message (rc=%s)\n' "$hwg_rc" >&2
    FAIL=$((FAIL + 1))
fi
if printf '%s\n' '{"tool_name":"Bash","tool_input":{"command":"herdr worktree create --branch x --cwd /repo"}}' \
        | "$HWG" >/dev/null 2>/tmp/claude-hook-test.err \
        && [ ! -s /tmp/claude-hook-test.err ]; then
    printf 'PASS  hwg: allow is exit 0 and silent\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: allow is exit 0 and silent\n' >&2
    FAIL=$((FAIL + 1))
fi

# Static registration: the template's PreToolUse Bash group must list the
# guards in this exact order (the new guard last, after push_guard).
# Independent of live machine state; the live drift check below is derived
# from the template and covers reconciled machines.
if python3 - <<'PY'
import json
import sys

tmpl = json.load(open("claude/settings.json.tmpl"))["hooks"]["PreToolUse"]
cmds = [h["command"] for e in tmpl if e.get("matcher") == "Bash" for h in e["hooks"]]
want = [
    "~/.claude/hooks/commit_guard.py",
    "~/.claude/hooks/no_ai_attribution_bash.py",
    "~/.claude/hooks/push_guard.py",
    "~/.claude/hooks/herdr_worktree_guard.py",
    "~/.claude/hooks/rm_guard.py",
]
sys.exit(0 if cmds == want else 1)
PY
then
    printf 'PASS  hwg: template lists the Bash guards in order, worktree guard last\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  hwg: template lists the Bash guards in order, worktree guard last\n' >&2
    FAIL=$((FAIL + 1))
fi

# Account-leaking ECC hooks: ECC 2.2.1 resolves several hook state paths
# through os.homedir() or $HOME/.claude, ignoring CLAUDE_CONFIG_DIR, so both
# accounts would share them. Hooks with an upstream env knob are scoped per
# config dir by the token key below; the seven ids here have no usable knob
# and are switched off. Exact set: nothing else may ride along, none may be
# missing.
# See claude/hooks/ecc-hook-isolation.test.sh for the behavioural proof.
if python3 - <<'PY'
import json
import sys

env = json.load(open("claude/settings.json.tmpl")).get("env") or {}
ids = {s.strip().lower() for s in env.get("ECC_DISABLED_HOOKS", "").split(",") if s.strip()}
want = {
    "session-start:plan-canvas-sessions",
    "stop:plan-canvas-pending",
    "post:bash:command-log-audit",
    "post:bash:command-log-cost",
    "post:skill:track",
    "pre:mcp-health-check",
    "post:mcp-health-check",
}
sys.exit(0 if ids == want else 1)
PY
then
    printf 'PASS  isolation: template excludes exactly the seven account-leaking ECC hook ids\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  isolation: template excludes exactly the seven account-leaking ECC hook ids\n' >&2
    FAIL=$((FAIL + 1))
fi

# The per-account key must carry the literal token in the template;
# reconcile_claude_settings_file resolves it per config dir.
if python3 - <<'PY'
import json
import sys

env = json.load(open("claude/settings.json.tmpl")).get("env") or {}
sys.exit(0 if env.get("ECC_AGENT_DATA_HOME") == "{{CLAUDE_CONFIG_DIR}}" else 1)
PY
then
    printf 'PASS  isolation: template carries the config-dir token in ECC_AGENT_DATA_HOME\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  isolation: template carries the config-dir token in ECC_AGENT_DATA_HOME\n' >&2
    FAIL=$((FAIL + 1))
fi

# Permissions floor: the template must not ask (or allow) for rm, so auto
# mode's classifier decides scratch cleanup; must keep the force-push and
# Jira-create ask rules; and must deny the literal root / home / .git
# removal shapes, which block in every mode. Static: independent of live
# machine state (the live drift check below covers reconciled machines).
if python3 - <<'PY'
import json
import sys

p = json.load(open("claude/settings.json.tmpl"))["permissions"]
sys.exit(0 if "Bash(rm:*)" not in p["ask"] and "Bash(rm:*)" not in p["allow"] else 1)
PY
then
    printf 'PASS  permissions: template has no rm ask or allow rule\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  permissions: template has no rm ask or allow rule\n' >&2
    FAIL=$((FAIL + 1))
fi
if python3 - <<'PY'
import json
import sys

p = json.load(open("claude/settings.json.tmpl"))["permissions"]
want = [
    "Bash(git push --force:*)",
    "Bash(git push -f:*)",
    "Bash(git push --force-with-lease:*)",
    "Bash(git push --mirror:*)",
    "mcp__plugin_atlassian_atlassian__createJiraIssue",
]
sys.exit(0 if p["ask"] == want else 1)
PY
then
    printf 'PASS  permissions: template ask list is exactly force-push plus Jira create\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  permissions: template ask list is exactly force-push plus Jira create\n' >&2
    FAIL=$((FAIL + 1))
fi
if python3 - <<'PY'
import json
import sys

p = json.load(open("claude/settings.json.tmpl"))["permissions"]
sys.exit(0 if p["deny"] == [] else 1)
PY
then
    printf 'PASS  permissions: template deny floor is empty (rm_guard.py replaces it)\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  permissions: template deny floor is empty (rm_guard.py replaces it)\n' >&2
    FAIL=$((FAIL + 1))
fi

# rm_guard.py: runs the real hook (not a rule-model simulation) against the
# catastrophic shapes a literal deny-floor pattern cannot express (finding
# F1: glob-under-root/home/.git, system paths, compound commands, variable
# targets) and against the harmless scratch-cleanup shapes it must not block.
RMG=claude/hooks/rm_guard.py
# Mostly-synthetic paths, not real directories -- the hook is pure string
# logic for every check except the git-worktree-root branch (N3 below),
# which stats `<cwd>/.git` and so needs a real temp directory. Deliberately
# outside /tmp, /var, and /private so the fixture cwd itself does not
# collide with the system-path denial.
RMG_HOME="/Users/rmg-test-user"
RMG_CWD="$RMG_HOME/proj"
rmg_payload() {
    printf '{"tool_name":"Bash","tool_input":{"command":"%s"},"cwd":"%s"}' "$1" "$RMG_CWD"
}
rmg_payload_at() {
    printf '{"tool_name":"Bash","tool_input":{"command":"%s"},"cwd":"%s"}' "$1" "$2"
}
rmg_blocks() {
    label="$1"
    cmd="$2"
    if printf '%s' "$(rmg_payload "$cmd")" | HOME="$RMG_HOME" "$RMG" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err; then
        printf 'FAIL  rmg: %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  rmg: %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}
rmg_allows() {
    label="$1"
    cmd="$2"
    if printf '%s' "$(rmg_payload "$cmd")" | HOME="$RMG_HOME" "$RMG" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err; then
        printf 'PASS  rmg: %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  rmg: %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}
rmg_blocks_at() {
    label="$1"
    cmd="$2"
    cwd="$3"
    home="${4:-$RMG_HOME}"
    if printf '%s' "$(rmg_payload_at "$cmd" "$cwd")" | HOME="$home" "$RMG" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err; then
        printf 'FAIL  rmg: %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    else
        printf 'PASS  rmg: %s\n' "$label"
        PASS=$((PASS + 1))
    fi
}
rmg_allows_at() {
    label="$1"
    cmd="$2"
    cwd="$3"
    home="${4:-$RMG_HOME}"
    if printf '%s' "$(rmg_payload_at "$cmd" "$cwd")" | HOME="$home" "$RMG" >/tmp/claude-hook-test.out 2>/tmp/claude-hook-test.err; then
        printf 'PASS  rmg: %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  rmg: %s\n' "$label" >&2
        FAIL=$((FAIL + 1))
    fi
}

# F1 bypass shapes: every one a literal deny-floor pattern cannot express.
rmg_blocks "blocks rm -rf /*" 'rm -rf /*'
rmg_blocks "blocks rm -rf ~/*" 'rm -rf ~/*'
rmg_blocks "blocks rm -rf \$HOME/*" 'rm -rf $HOME/*'
rmg_blocks "blocks rm -rf .git/*" 'rm -rf .git/*'
rmg_blocks "blocks rm -rf /bin" 'rm -rf /bin'
rmg_blocks "blocks rm -rf /etc" 'rm -rf /etc'
rmg_blocks "blocks rm -rf /usr /bin" 'rm -rf /usr /bin'
rmg_blocks "blocks rm -fr --no-preserve-root /*" 'rm -fr --no-preserve-root /*'
rmg_blocks "blocks compound cd / && rm -rf *" 'cd / && rm -rf *'
rmg_blocks 'blocks rm -rf $X with unexpanded variable target' 'rm -rf $X'
rmg_blocks "blocks compound command split on ;" 'echo hi; rm -rf /*'
rmg_blocks "blocks compound command split on |" 'true | rm -rf /*'

# Harmless scratch-cleanup shapes must not be blocked.
rmg_allows "allows rm -rf dist/ build/" 'rm -rf dist/ build/'
rmg_allows "allows rm -rf ./.github" 'rm -rf ./.github'
rmg_allows "allows rm ./file~" 'rm ./file~'
rmg_allows "allows rm -rf node_modules" 'rm -rf node_modules'
rmg_allows "allows rm -rf ~/proj/build" 'rm -rf ~/proj/build'
rmg_allows 'allows rm -rf $HOME/.cache/x' 'rm -rf $HOME/.cache/x'
rmg_allows "allows rm -rf .git/index.lock" 'rm -rf .git/index.lock'
rmg_allows "allows non-rm command" 'echo rm -rf /'
if printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"notes.md"}}' \
        | HOME="$RMG_HOME" "$RMG"; then
    printf 'PASS  rmg: allows non-Bash tool\n'
    PASS=$((PASS + 1))
else
    printf 'FAIL  rmg: allows non-Bash tool\n' >&2
    FAIL=$((FAIL + 1))
fi

# round-2 review BF1: shell-wrapper passthrough (sh/bash/zsh -c, and nested
# wrappers) must be unwrapped and the inner script re-parsed.
rmg_blocks "blocks rm -rf /* wrapped in sh -c" "sh -c 'rm -rf /*'"
rmg_blocks "blocks rm -rf / wrapped in bash -c" "bash -c 'rm -rf /'"
rmg_blocks "blocks rm -rf /etc wrapped in zsh -c" "zsh -c 'rm -rf /etc'"
rmg_blocks "blocks sh -c rm wrapped in nohup" "nohup sh -c 'rm -rf /*'"
rmg_blocks "blocks bash -c rm wrapped in time" "time bash -c 'rm -rf /etc'"
rmg_blocks "blocks sh -c rm wrapped in env" "env sh -c 'rm -rf /'"
rmg_blocks "blocks sh -c rm wrapped in nice" "nice sh -c 'rm -rf /'"
rmg_blocks "blocks sh -c rm wrapped in nested env+nohup" "env nohup bash -c 'rm -rf /etc'"
rmg_blocks "blocks compound command inside sh -c" "sh -c 'ls; rm -rf /'"
rmg_allows "allows harmless sh -c command" "sh -c 'echo hi'"
rmg_allows "allows narrow rm inside bash -c" "bash -c 'rm -rf ./build'"

# round-2 review BF2: brace-expanded targets must expand before classifying.
rmg_blocks "blocks rm -rf /{,bin} (brace includes root)" 'rm -rf /{,bin}'
rmg_blocks "blocks rm -rf /{bin,etc,usr} (brace includes system path)" 'rm -rf /{bin,etc,usr,var,lib,opt}'
rmg_blocks "blocks rm -rf /b{i,i}n (brace resolves to system path)" 'rm -rf /b{i,i}n'
rmg_allows "allows rm -rf ~/{.ssh,Documents} (named subdirs, not catastrophic)" 'rm -rf ~/{.ssh,Documents}'

# round-2 review BF3: `(` subshell groups and `cd ...;` must track cwd like
# the unparenthesized `&&` form already does.
rmg_blocks "blocks (cd / && rm -rf *) subshell" '(cd / && rm -rf *)'
rmg_blocks "blocks ( cd /usr && rm -rf * ) with spaces" '( cd /usr && rm -rf * )'
rmg_blocks "blocks (cd /etc && rm -rf *) subshell" '(cd /etc && rm -rf *)'
rmg_blocks "blocks cd /; rm -rf * split on semicolon" 'cd /; rm -rf *'

# round-2 review BF4: repeated slashes and .././. components must normalize
# to reach the same root/system-path check as their canonical form.
rmg_blocks "blocks rm -rf // (double-slash root)" 'rm -rf //'
rmg_blocks "blocks rm -rf //* (double-slash root glob)" 'rm -rf //*'
rmg_blocks "blocks rm -rf /./ (dot component)" 'rm -rf /./'
rmg_blocks "blocks rm -rf /x/../ (dot-dot component)" 'rm -rf /x/../'

# round-2 review N1: macOS aliases /tmp->/private/tmp and /var->/private/var,
# so scratch/mktemp cleanup under either spelling must stay allowed while
# real system paths under /var remain blocked.
rmg_allows "allows \$TMPDIR-style /var/folders cleanup" 'rm -rf /var/folders/pk/xxxx/T/tmp.abc'
rmg_allows "allows /private/tmp scratch cleanup" 'rm -rf /private/tmp/mybuild'
rmg_allows "allows /tmp scratch cleanup" 'rm -rf /tmp/scratch'
rmg_blocks "blocks /var/db (real system path, not scratch)" 'rm -rf /var/db'

# round-2 review N2: previously-untested denial branches.
rmg_blocks "blocks exact rm -rf / (no glob needed)" 'rm -rf /'
rmg_blocks "blocks exact rm -rf ~ (no glob needed)" 'rm -rf ~'
rmg_blocks 'blocks exact rm -rf $HOME (no glob needed)' 'rm -rf $HOME'
rmg_blocks "blocks exact rm -rf .git (dir itself, no glob)" 'rm -rf .git'
rmg_blocks_at "blocks rm -rf on a parent of a deeper cwd" \
    "rm -rf $RMG_HOME/proj" "$RMG_HOME/proj/sub/deep"

# round-2 review N3: `rm -rf .`/`rm -rf ./` at a git worktree root or home
# must be denied; the same command elsewhere is an intentional allow.
RMG_GITROOT=$(mktemp -d)
trap 'rm -rf "$RMG_GITROOT"' EXIT
: > "$RMG_GITROOT/.git"
rmg_blocks_at "blocks rm -rf . at a git worktree root" 'rm -rf .' "$RMG_GITROOT"
rmg_blocks_at "blocks rm -rf ./ at a git worktree root" 'rm -rf ./' "$RMG_GITROOT"
rmg_blocks_at "blocks rm -rf . at HOME" 'rm -rf .' "$RMG_HOME" "$RMG_HOME"
RMG_PLAIN=$(mktemp -d)
trap 'rm -rf "$RMG_GITROOT" "$RMG_PLAIN"' EXIT
rmg_allows_at "allows rm -rf . in a plain (non-git, non-home) scratch dir" 'rm -rf .' "$RMG_PLAIN"
rm -rf "$RMG_GITROOT" "$RMG_PLAIN"
trap - EXIT

# account_guard.py account-aware routing. Fixtures use synthetic account tokens
# in throwaway HOMEs -- no real credentials, no employer strings.
GUARD_FIX=$(mktemp -d)
trap 'rm -rf "$GUARD_FIX"' EXIT

# Fixture A: the default ~/.claude dir is signed into the WORK account (the
# IDE-launch machine that produced the original false positive). Work identity
# lives in the home-root ~/.claude.json legacy fallback.
mkdir -p "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/.claude" \
    "$GUARD_FIX/a/Git/work/repo" "$GUARD_FIX/a/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/a/.claude.json"

guard_case "guard: IDE launch, work account on work repo -> silent (false positive fixed)" \
    silent "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/work/repo"
guard_case "guard: IDE launch, work account on personal repo -> warn (blind spot caught)" \
    warn "$GUARD_FIX/a" "" "$GUARD_FIX/a/Git/personal/repo"
guard_case "guard: wrapper launch, work dir on work repo -> silent" \
    silent "$GUARD_FIX/a" "$GUARD_FIX/a/.claude-work" "$GUARD_FIX/a/Git/work/repo"

# Fixture B: clean separation -- default ~/.claude signed into a personal
# account, ~/.claude-work into the work account.
mkdir -p "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/.claude" \
    "$GUARD_FIX/b/Git/work/repo" "$GUARD_FIX/b/Git/personal/repo"
printf '{"oauthAccount":{"accountUuid":"work-uuid"}}' > "$GUARD_FIX/b/.claude-work/.claude.json"
printf '{"oauthAccount":{"accountUuid":"personal-uuid"}}' > "$GUARD_FIX/b/.claude.json"

guard_case "guard: personal account on personal repo -> silent" \
    silent "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/personal/repo"
guard_case "guard: personal account on work repo -> warn" \
    warn "$GUARD_FIX/b" "" "$GUARD_FIX/b/Git/work/repo"
guard_case "guard: wrapper launch, work account on work repo -> silent" \
    silent "$GUARD_FIX/b" "$GUARD_FIX/b/.claude-work" "$GUARD_FIX/b/Git/work/repo"

# Fixture C: no work login at all (cloud container / personal-only machine).
# Account cannot be resolved -> falls back to the original path-based check.
mkdir -p "$GUARD_FIX/c/.claude" \
    "$GUARD_FIX/c/Git/work/repo" "$GUARD_FIX/c/Git/personal/repo"

guard_case "guard: fallback path check, default dir on work repo -> warn" \
    warn "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/work/repo"
guard_case "guard: fallback path check, default dir on personal repo -> silent" \
    silent "$GUARD_FIX/c" "" "$GUARD_FIX/c/Git/personal/repo"

# Settings drift: hand-merged machines that missed a SessionStart hook
# entry must fail visibly instead of silently lacking the account-mismatch
# guard. Both account config dirs carry their own machine-local settings.json
# (~/.claude personal, ~/.claude-work work); check every one that exists.
# Skipped when no live settings file exists (fresh machine or CI).
for settings_dir in "$HOME/.claude" "$HOME/.claude-work"; do
    if [ -f "$settings_dir/settings.json" ]; then
        # Every hook command the template registers, for every event, must be
        # registered live. Derived from the template so a new hook can never
        # be invisible to this check.
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

live = json.load(open(os.environ["SETTINGS_PATH"])).get("hooks", {})
tmpl = json.load(open("claude/settings.json.tmpl")).get("hooks", {})
missing = []
for event, entries in tmpl.items():
    wanted = [h.get("command", "") for e in entries for h in e.get("hooks", [])]
    got = [h.get("command", "") for e in live.get(event, []) for h in e.get("hooks", [])]
    for cmd in wanted:
        if cmd not in got:
            missing.append(event + ": " + cmd)
for entry in missing:
    print("  missing hook: " + entry)
sys.exit(1 if missing else 0)
PY
        then
            printf 'PASS  settings: %s registers every template hook\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s missing template hooks (run update to reconcile)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi

        # Permissions drift: the reconcile treats permissions as a
        # template-owned key (reasserted wholesale on every update), so live
        # permissions must equal the template's. A mismatch means the machine
        # missed an update and may silently retain retired broad grants.
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

live = json.load(open(os.environ["SETTINGS_PATH"])).get("permissions") or {}
tmpl = json.load(open("claude/settings.json.tmpl")).get("permissions") or {}
if live == tmpl:
    sys.exit(0)
for key in sorted(set(live) | set(tmpl)):
    lv, tv = live.get(key), tmpl.get(key)
    if lv == tv:
        continue
    if isinstance(lv, list) and isinstance(tv, list):
        for rule in sorted(set(lv) - set(tv)):
            print("  " + key + " live-only rule: " + rule)
        for rule in sorted(set(tv) - set(lv)):
            print("  " + key + " missing rule:   " + rule)
    else:
        print("  " + key + ": live=" + repr(lv) + " template=" + repr(tv))
sys.exit(1)
PY
        then
            printf 'PASS  settings: %s permissions match template\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s permissions drifted (update reconciles: template rules reassert, live-only grants are DROPPED -- commit intentional grants to the template)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi

        # Exclusion drift: env is template-owned, so a reconciled machine must
        # carry all seven excluded ids. Superset check so a machine-local extra
        # id does not fail here (the reconcile would drop it on the next
        # update anyway).
        if SETTINGS_PATH="$settings_dir/settings.json" python3 - <<'PY'
import json
import os
import sys

env = json.load(open(os.environ["SETTINGS_PATH"])).get("env") or {}
ids = {s.strip().lower() for s in env.get("ECC_DISABLED_HOOKS", "").split(",") if s.strip()}
want = {
    "session-start:plan-canvas-sessions",
    "stop:plan-canvas-pending",
    "post:bash:command-log-audit",
    "post:bash:command-log-cost",
    "post:skill:track",
    "pre:mcp-health-check",
    "post:mcp-health-check",
}
for missing in sorted(want - ids):
    print("  missing exclusion: " + missing)
sys.exit(0 if want <= ids else 1)
PY
        then
            printf 'PASS  settings: %s excludes the account-leaking ECC hooks\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s does not exclude the account-leaking ECC hooks (run update to reconcile)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi

        # Scope drift: the per-account key must resolve to THIS config dir
        # (abspath, not realpath -- reconcile uses abspath too), and no
        # unsubstituted token may remain anywhere in env.
        if SETTINGS_PATH="$settings_dir/settings.json" SETTINGS_DIR="$settings_dir" python3 - <<'PY'
import json
import os
import sys

env = json.load(open(os.environ["SETTINGS_PATH"])).get("env") or {}
cfg = os.path.abspath(os.environ["SETTINGS_DIR"])
tmpl_env = json.load(open("claude/settings.json.tmpl")).get("env") or {}
ok = True
want = str(tmpl_env.get("ECC_AGENT_DATA_HOME", "")).replace("{{CLAUDE_CONFIG_DIR}}", cfg)
got = env.get("ECC_AGENT_DATA_HOME")
if got != want:
    print("  ECC_AGENT_DATA_HOME: live=" + repr(got) + " want=" + repr(want))
    ok = False
for key, value in env.items():
    if isinstance(value, str) and "{{CLAUDE_CONFIG_DIR}}" in value:
        print("  unsubstituted token in " + key)
        ok = False
sys.exit(0 if ok else 1)
PY
        then
            printf 'PASS  settings: %s scopes ECC state to this config dir\n' "$settings_dir"
            PASS=$((PASS + 1))
        else
            printf 'FAIL  settings: %s does not scope ECC state to this config dir (run update to reconcile)\n' "$settings_dir" >&2
            FAIL=$((FAIL + 1))
        fi
    else
        printf 'SKIP  settings: no live %s/settings.json\n' "$settings_dir"
    fi
done

# herdr_stop_gate.py: exit 2 (refuse) when an orchestrated worker stops
# without its completion record, 0 otherwise. Every fixture is a throwaway
# config dir under mktemp with the documented herdr-orch layout; the hook
# must never write into it (checked by the read-only case at the end).
HSG=claude/hooks/herdr_stop_gate.py
GATE_SID=11111111-1111-1111-1111-111111111111
GATE_P_F='{"hook_event_name":"Stop","session_id":"11111111-1111-1111-1111-111111111111","stop_hook_active":false}'
GATE_LAST=

# gate_fixture DIR WS ROLE REC MARKERS
#   ROLE    impl | review | mech | noindex (no workspaces/<ws>.json)
#   REC     comma list: none | notask (no tasks/PROJ-1.json) | dirtask (a
#           directory in its place) | mechentry (a later mech workers[]
#           entry on the same workspace) | <done|review>:<fresh|stale|badts>:<ws>:<task>
#   MARKERS nofile | dup (two transcripts) | N lines in projects/p/<sid>.jsonl
gate_fixture() {
    python3 - "$1" "$2" "$3" "$4" "$5" <<'PY'
import json,os,sys
root,ws,role,rec,markers=sys.argv[1:6]
SID="11111111-1111-1111-1111-111111111111"
rd=os.path.join(root,"herdr-orch","slug-x")
os.makedirs(os.path.join(rd,"workspaces"));os.makedirs(os.path.join(rd,"tasks"))
parts=rec.split(",")
if role!="noindex":
    json.dump({"task_id":"PROJ-1","repo_slug":"slug-x","role":role},open(os.path.join(rd,"workspaces",ws+".json"),"w"))
if "dirtask" in parts:
    os.makedirs(os.path.join(rd,"tasks","PROJ-1.json"))
elif "notask" not in parts:
    workers=[{"role":"impl","phase":"implement","workspace_id":ws,"agent":"impl-proj-1","ts":"2026-09-06T12:00:00Z"}]
    if role=="review":
        workers.append({"role":"review","phase":"review","workspace_id":ws,"agent":"rev-proj-1","ts":"2026-09-06T12:30:00Z"})
    if "mechentry" in parts:
        workers.append({"role":"mech","phase":"implement","workspace_id":ws,"agent":"mech-proj-1","launch_id":"mech-proj-1-20260906T140000Z","ts":"2026-09-06T14:00:00Z"})
    json.dump({"v":1,"task_id":"PROJ-1","base_sha":"b"*40,"workers":workers},open(os.path.join(rd,"tasks","PROJ-1.json"),"w"))
for spec in parts:
    if spec in ("none","notask","dirtask","mechentry"):
        continue
    kind,when,who,tid=spec.split(":")
    ts={"fresh":"2026-09-06T13:00:00Z","stale":"2026-09-06T11:00:00Z","badts":"2026-09-06 13:00:00"}[when]
    json.dump({"v":1,"task_id":tid,"workspace_id":who,"phase":"implement","outcome":"completed","ts":ts},open(os.path.join(rd,"tasks","PROJ-1."+kind+".json"),"w"))
if markers!="nofile":
    line='{"type":"user","message":{"role":"user","content":"Stop hook feedback: herdr-stop-gate: blocked (1 of 2)"}}\n'
    dirs=["p","q"] if markers=="dup" else ["p"]
    n=1 if markers=="dup" else int(markers)
    for d in dirs:
        os.makedirs(os.path.join(root,"projects",d))
        open(os.path.join(root,"projects",d,SID+".jsonl"),"w").write(line*n)
PY
}

# gate_case LABEL EXPECT WS ROLE REC MARKERS PAYLOAD [NAME=VALUE ...]
#   EXPECT  allow | block-N (refusal number N) | release-<text on stdout>
#   Trailing NAME=VALUE pairs override the environment (HERDR_ENV= unsets
#   the herdr flag for the hook's purposes). GATE_LAST keeps the fixture
#   dir so a caller can inspect out/err afterwards.
gate_case() {
    label="$1"; expect="$2"; ws="$3"; role="$4"; rec="$5"; markers="$6"; payload="$7"; shift 7
    gd=$(mktemp -d)
    gate_fixture "$gd" "$ws" "$role" "$rec" "$markers"
    # The suite runs under set -e: a refusing hook must sit inside an if.
    if printf '%s' "$payload" | env CLAUDE_CONFIG_DIR="$gd" HERDR_ENV=1 HERDR_WORKSPACE_ID="$ws" "$@" "$HSG" >"$gd/out" 2>"$gd/err"; then
        rc=0
    else
        rc=$?
    fi
    ok=0
    case "$expect" in
        allow)
            [ "$rc" = 0 ] && [ ! -s "$gd/out" ] && [ ! -s "$gd/err" ] && ok=1 ;;
        block-*)
            [ "$rc" = 2 ] && [ ! -s "$gd/out" ] && [ "$(wc -l <"$gd/err" | tr -d ' ')" = 3 ] \
                && head -n 1 "$gd/err" | grep -q "^herdr-stop-gate: blocked (${expect#block-} of 2) -- emit-done (or emit-review) before stopping; the orchestrator only recognizes the record\.$" \
                && sed -n 3p "$gd/err" | grep -q '^Then stop again\. The gate releases after 2 blocks even without a record\.$' \
                && ok=1 ;;
        release-*)
            [ "$rc" = 0 ] && [ ! -s "$gd/err" ] && grep -q 'herdr-stop-gate: released' "$gd/out" \
                && grep -q "${expect#release-}" "$gd/out" && ok=1 ;;
    esac
    if [ "$ok" = 1 ]; then
        printf 'PASS  gate: %s\n' "$label"
        PASS=$((PASS + 1))
    else
        printf 'FAIL  gate: %s (rc=%s out=%s err=%s)\n' "$label" "$rc" "$(cat "$gd/out")" "$(head -n 1 "$gd/err")" >&2
        FAIL=$((FAIL + 1))
    fi
    GATE_LAST="$gd"
}

gate_case "impl worker without record is refused" block-1 w1 impl none nofile "$GATE_P_F"
if sed -n 2p "$GATE_LAST/err" | grep -Fxq 'Run: python3 ${CLAUDE_CONFIG_DIR:-$HOME/.claude}/hooks/herdr_orch_core.py emit-done --repo-slug slug-x --task-id PROJ-1 --workspace w1 --agent impl-proj-1 --phase implement --outcome completed|failed|paused --head-sha "$(git rev-parse HEAD)" --base-sha bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'; then
    printf 'PASS  gate: refusal prints the filled emit-done line\n'; PASS=$((PASS + 1))
else
    printf 'FAIL  gate: refusal prints the filled emit-done line (got: %s)\n' "$(sed -n 2p "$GATE_LAST/err")" >&2; FAIL=$((FAIL + 1))
fi
gate_case "impl worker with own fresh record is allowed" allow w1 impl done:fresh:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "record from another workspace is refused" block-1 w1 impl done:fresh:w9:PROJ-1 nofile "$GATE_P_F"
gate_case "record for another task is refused" block-1 w1 impl done:fresh:w1:PROJ-2 nofile "$GATE_P_F"
gate_case "review worker is refused by a done record" block-1 w1 review done:fresh:w1:PROJ-1 nofile "$GATE_P_F"
if sed -n 2p "$GATE_LAST/err" | grep -Fxq 'Run: python3 ${CLAUDE_CONFIG_DIR:-$HOME/.claude}/hooks/herdr_orch_core.py emit-review --repo-slug slug-x --task-id PROJ-1 --workspace w1 --agent rev-proj-1 --reviewed-head-sha "$(git rev-parse HEAD)" --outcome approved|changes-requested --blocking-count <n> --findings-ref <path>'; then
    printf 'PASS  gate: review refusal prints the filled emit-review line\n'; PASS=$((PASS + 1))
else
    printf 'FAIL  gate: review refusal prints the filled emit-review line (got: %s)\n' "$(sed -n 2p "$GATE_LAST/err")" >&2; FAIL=$((FAIL + 1))
fi
gate_case "review worker with review record is allowed" allow w1 review review:fresh:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "impl worker is refused by a review record alone" block-1 w1 impl review:fresh:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "missing task record prints placeholders" block-1 w1 impl notask nofile "$GATE_P_F"
if sed -n 2p "$GATE_LAST/err" | grep -Fq -- '--agent <agent> --phase <phase> --outcome completed|failed|paused --head-sha "$(git rev-parse HEAD)" --base-sha <base_sha>'; then
    printf 'PASS  gate: placeholders stand in for missing task record fields\n'; PASS=$((PASS + 1))
else
    printf 'FAIL  gate: placeholders stand in for missing task record fields (got: %s)\n' "$(sed -n 2p "$GATE_LAST/err")" >&2; FAIL=$((FAIL + 1))
fi
gate_case "no HERDR_ENV is allowed" allow w1 impl none nofile "$GATE_P_F" HERDR_ENV=
gate_case "no index for the workspace is allowed" allow w1 noindex none nofile "$GATE_P_F"
gate_case "invalid workspace id is allowed" allow ..x impl none nofile "$GATE_P_F"
gate_case "mech role is allowed" allow w1 mech none nofile "$GATE_P_F"
gate_case "non-Stop payload is allowed" allow w1 impl none nofile '{"hook_event_name":"Notification","notification_type":"permission_prompt"}'
gate_case "non-JSON stdin is allowed" allow w1 impl none nofile 'not json'
gate_case "JSON array stdin is allowed" allow w1 impl none nofile '[]'
gate_case "stale record from before launch is refused" block-1 w1 impl done:stale:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "record with unparseable ts is refused" block-1 w1 impl done:badts:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "record accepted when launch time is unknown" allow w1 impl notask,done:fresh:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "unreadable task record makes launch unknown" allow w1 impl dirtask,done:fresh:w1:PROJ-1 nofile "$GATE_P_F"
gate_case "unreadable task record still refuses without record" block-1 w1 impl dirtask nofile "$GATE_P_F"
gate_case "later mech entry does not move the launch time" allow w1 impl mechentry,done:fresh:w1:PROJ-1 nofile "$GATE_P_F"
if python3 - <<'PY'
import importlib.util
from datetime import datetime, timezone
spec = importlib.util.spec_from_file_location("g", "claude/hooks/herdr_stop_gate.py")
g = importlib.util.module_from_spec(spec)
spec.loader.exec_module(g)
utc = timezone.utc
assert g.parse_ts("2026-09-06T18:38:51Z") == datetime(2026, 9, 6, 18, 38, 51, tzinfo=utc)
assert g.parse_ts("2026-09-06T18:38:51") == datetime(2026, 9, 6, 18, 38, 51, tzinfo=utc)
assert g.parse_ts("2026-09-06T18:38:51.921Z") == datetime(2026, 9, 6, 18, 38, 51, tzinfo=utc)
assert g.parse_ts("2026-09-06T18:38:51+02:00") == datetime(2026, 9, 6, 16, 38, 51, tzinfo=utc)
assert g.parse_ts("2026-09-06T18:38:51-0130") == datetime(2026, 9, 6, 20, 8, 51, tzinfo=utc)
for bad in ("2026-09-06", "2026-09-06 18:38:51Z", "", None, 5, "2026-13-06T18:38:51Z", "2026-09-06T18:38:51Zx"):
    assert g.parse_ts(bad) is None, bad
assert g.launch_time({"started": "2026-09-06T12:00:00Z", "ts": "2026-09-06T13:00:00Z"}) == datetime(2026, 9, 6, 12, 0, 0, tzinfo=utc)
assert g.launch_time({"started": "garbage", "ts": "2026-09-06T13:00:00Z"}) is None
assert g.launch_time({"ts": "2026-09-06T13:00:00Z"}) == datetime(2026, 9, 6, 13, 0, 0, tzinfo=utc)
assert g.launch_time({}) is None and g.launch_time(None) is None
PY
then
    printf 'PASS  gate: parse_ts and launch_time follow the spec parser\n'; PASS=$((PASS + 1))
else
    printf 'FAIL  gate: parse_ts and launch_time follow the spec parser\n' >&2; FAIL=$((FAIL + 1))
fi

GATE_P_T='{"hook_event_name":"Stop","session_id":"11111111-1111-1111-1111-111111111111","stop_hook_active":true}'
gate_case "second refusal counts the transcript" block-2 w1 impl none 1 "$GATE_P_T"
gate_case "released after two refusals" "release-cap reached" w1 impl none 2 "$GATE_P_T"
if python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); m=d.get("systemMessage"); sys.exit(0 if isinstance(m, str) and "PROJ-1" in m and list(d) == ["systemMessage"] else 1)' "$GATE_LAST/out"; then
    printf 'PASS  gate: release is one systemMessage object naming the task\n'; PASS=$((PASS + 1))
else
    printf 'FAIL  gate: release is one systemMessage object naming the task (got: %s)\n' "$(cat "$GATE_LAST/out")" >&2; FAIL=$((FAIL + 1))
fi
gate_case "released when transcript is missing" "release-transcript unavailable" w1 impl none nofile "$GATE_P_T"
gate_case "released when transcript has no marker" "release-transcript evidence missing" w1 impl none 0 "$GATE_P_T"
gate_case "released when two transcripts match the session" "release-transcript unavailable" w1 impl none dup "$GATE_P_T"
gate_case "released when the session id is unsafe" "release-transcript unavailable" w1 impl none 2 '{"hook_event_name":"Stop","session_id":"../x","stop_hook_active":true}'
gate_case "fresh cycle is refused again after a release" block-3 w1 impl none 2 "$GATE_P_F"
gate_case "active hook with a fresh record is allowed silently" allow w1 impl done:fresh:w1:PROJ-1 2 "$GATE_P_T"
gate_case "stop_hook_active must be boolean true to release" block-3 w1 impl none 2 '{"hook_event_name":"Stop","session_id":"11111111-1111-1111-1111-111111111111","stop_hook_active":"true"}'

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
